name: vfr_light
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^0.12.0
  enviro_sensors: ^1.0.1
  geolocator: ^7.0.3
  font_awesome_flutter: ^9.0.0
  path_provider: ^2.0.1
  wakelock: ^0.5.1
  flutter_foreground_plugin: ^0.8.0
  cached_network_image: ^3.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/offline_layers/oaci_vfr/8/
    - assets/offline_layers/oaci_vfr/9/
    - assets/offline_layers/oaci_vfr/10/
    - assets/offline_layers/oaci_vfr/11/
    - assets/survol.png
